config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 get '/second_page', to: 'pages#second_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def second_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container main">
  <div class="title">
    <h1>My Profile Homepage</h1>
  </div>
  <br>
  <button type="button" class="btn btn-primary">
    <%= link_to 'Profile Under Construction With Bootstrap', second_page_path, :class => "btn" %>
  </button>
</div>

app/views/pages/second_page.html.erb
<div class="container main">
  <h1>My Profile Homepage</h1>
  <br>
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Profile</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-education-tab" data-bs-toggle="pill" data-bs-target="#pills-education" type="button" role="tab" aria-controls="pills-education" aria-selected="false">Education</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-experience-tab" data-bs-toggle="pill" data-bs-target="#pills-experience" type="button" role="tab" aria-controls="pills-experience" aria-selected="false">Work Experience</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-programs-tab" data-bs-toggle="pill" data-bs-target="#pills-programs" type="button" role="tab" aria-controls="pills-programs" aria-selected="true">My Programs</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-hobbies-tab" data-bs-toggle="pill" data-bs-target="#pills-hobbies" type="button" role="tab" aria-controls="pills-hobbies" aria-selected="true">Hobbies</button>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <div class="profile d-flex p-2 mb-4 justify-content-between rounded">
        <%= image_tag("foto.jpg", width: 350, height: 350) %>
        <p class="centered p-5">
          I´m a 43 year-old highly motivated <strong>Full Stack Web Developer</strong>. I consider myself a person with a high sense of responsibility,
          autonomous and proactive. I am a dedicated person who thrives on new challenges. My main goal is to change career and continue to
          improve my coding skills and keep on learning.
        </p>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-education" role="tabpanel" aria-labelledby="pills-education-tab">
      <div class="education d-inline-flex">
        <ul>
          <li>
            <div class="lewagon">
              <%= image_tag("logolewagon.svg", width: 200, height: 200) %>
              <p>
                LE WAGON – WEB DEVELOPER BOOTCAMP
                BATCH 845 IBERIA WEB PT
                2022
                24-week part-time intensive coding bootcamp learning HTML,
                CSS, Bootstrap, JavaScript E6, SQL, git, GitHub, Heroku and Ruby
                on Rails.
              </p>
            </div>
          </li>
          <li>
            <div class="university">
              <%= image_tag("logolusofona.jpg", width: 200, height: 200) %>
              <p>
              LANGUAGES_____
              PORTUGUESE (native)
              ENGLISH
              LUSÓFONA UNIVERSITY OF HUMANITIES AND
              TECHNOLOGIES
              DEGREE IN MATHEMATICS
              2009-2015
              Theoretical, methodological and pratical foundations in the
              areas of computer science and applied mathematics.
              </p>
            </div>
          </li>
          <li>
            <div class="tap">
            <%= image_tag("logotap.svg", with: 200, height: 200) %>
              <p>
                TAP AIR PORTUGAL
                AIRCRAFT MAINTENANCE TECHNICIANS
                AB-INITIO – ELECTROMECHANICAL
                2002-2003
                Carry out fault detection, repair and testing of systems. Perform
                preventive and corrective maintenance on aircraft, repairing,
                replacing and regulating equipment or components of electrical
                and mechanical systems.
              </p>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-experience" role="tabpanel" aria-labelledby="pills-experience-tab">
      <%= image_tag("logotap.svg", with: 200, height: 200) %>
      <p>
        TAP PORTUGAL
        AIRCRAFT MAINTENANCE TECHNICIAN
        2003-Present – 18 years 10 months
        Work as a certified Part 66 B1.1 Aircraft Maintenance Technician
        with the role of component testing, maintenance and overhaul
        for ATA 28 and ATA 70 components.
        Specialized in overhauling VBV Hydraulic Gear Motor; VSV
        Actuators ; VBV Actuatores ; HPTACC Valves ; Transient Bleed
        Valve ; HPTC Valve ; Turbine Clearance Control
      </p>
    </div>
    <div class="tab-pane fade" id="pills-programs" role="tabpanel" aria-labelledby="pills-programs-tab">
      <p>
       At the moment the programs that were deployed during the bootcamp on Heroku are offline because Heroku change some polices
       and are not free anymore. I'm researching the new Heroku and another plataforms to put them online again. Thank you for your understanding.
       <br>
       Link 1 <br>
       Link 2 <br>
       Link 3 <br>
      </p>
    </div>
    <div class="tab-pane fade" id="pills-hobbies" role="tabpanel" aria-labelledby="pills-hobbies-tab">
      <p>
       Hobbies
      </p>
    </div>
  </div>
  <button type="button" class="btn btn-primary">
    <%= link_to 'Back to Profile Without Bootstrap', root_path, :class => "btn" %>
  </button>
</div>

app/views/pages/third_page.html.erb
<h1>Second Page</h1>
<br>
<br>

<button type="button" class="btn btn-sucess">
  <%= link_to '1º página', root_path, :class => 'btn' %>
</button>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.linkedin.com/in/jo%C3%A3o-goncalo-pantoja-coutinho-bernardo-9a11b089/" target="_blank"><i class="fab fa-linkedin"></i></a>
    <a href="https://github.com/divinebolt" target="_blank"><i class="fab fa-github"></i></a>
    <%= mail_to "joaogoncalob@gmail.com" do %>
      <i class="fa-solid fa-envelope"></i>
    <% end %>
    <i class="fa-solid fa-phone">+351 92 660 72 35</i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-space">
  <div class="container ">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "LinkedIn", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "GitHub", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "foto.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>